package weibo

type AutoGenerated struct {
	Ok          int           `json:"ok"`
	FilterGroup []FilterGroup `json:"filter_group"`
	Data        []Data        `json:"data"`
	RootComment []interface{} `json:"rootComment"`
	TotalNumber int           `json:"total_number"`
	MaxID       int64         `json:"max_id"`
	TrendsText  string        `json:"trendsText"`
}

type FilterGroup struct {
	Param     string `json:"param"`
	Scheme    string `json:"scheme"`
	Title     string `json:"title"`
	IsDefault int    `json:"isDefault"`
}

type ExtendInfo struct {
	DanmakuMid string `json:"danmaku_mid"`
}
type User struct {
	ID                int64         `json:"id"`
	Idstr             string        `json:"idstr"`
	PcNew             int           `json:"pc_new"`
	ScreenName        string        `json:"screen_name"`
	ProfileImageURL   string        `json:"profile_image_url"`
	ProfileURL        string        `json:"profile_url"`
	Verified          bool          `json:"verified"`
	VerifiedType      int           `json:"verified_type"`
	Domain            string        `json:"domain"`
	Weihao            string        `json:"weihao"`
	AvatarLarge       string        `json:"avatar_large"`
	AvatarHd          string        `json:"avatar_hd"`
	FollowMe          bool          `json:"follow_me"`
	Following         bool          `json:"following"`
	Mbrank            int           `json:"mbrank"`
	Mbtype            int           `json:"mbtype"`
	VPlus             int           `json:"v_plus"`
	PlanetVideo       bool          `json:"planet_video"`
	Description       string        `json:"description"`
	Location          string        `json:"location"`
	Gender            string        `json:"gender"`
	FollowersCount    int           `json:"followers_count"`
	FollowersCountStr string        `json:"followers_count_str"`
	FriendsCount      int           `json:"friends_count"`
	StatusesCount     int           `json:"statuses_count"`
	URL               string        `json:"url"`
	Svip              int           `json:"svip"`
	Vvip              int           `json:"vvip"`
	CoverImagePhone   string        `json:"cover_image_phone"`
	IconList          []interface{} `json:"icon_list"`
}
type Data struct {
	CreatedAt          string        `json:"created_at"`
	ID                 int64         `json:"id"`
	Rootid             int64         `json:"rootid"`
	Rootidstr          string        `json:"rootidstr"`
	FloorNumber        int           `json:"floor_number"`
	Text               string        `json:"text"`
	DisableReply       int           `json:"disable_reply"`
	RestrictOperate    int           `json:"restrictOperate"`
	SourceAllowclick   int           `json:"source_allowclick"`
	SourceType         int           `json:"source_type"`
	Source             string        `json:"source"`
	ExtendInfo         ExtendInfo    `json:"extend_info"`
	User               User          `json:"user"`
	Mid                string        `json:"mid"`
	Idstr              string        `json:"idstr"`
	URLObjects         []interface{} `json:"url_objects"`
	Liked              bool          `json:"liked"`
	LiveBizCode        int           `json:"liveBizCode"`
	APIState           int           `json:"apiState"`
	ErrorNo            int           `json:"errorNo"`
	State              int           `json:"state"`
	Readtimetype       string        `json:"readtimetype"`
	AnalysisExtra      string        `json:"analysis_extra"`
	MatchAiPlayPicture bool          `json:"match_ai_play_picture"`
	Rid                string        `json:"rid"`
	AllowFollow        bool          `json:"allow_follow"`
	ItemCategory       string        `json:"item_category"`
	Comments           []interface{} `json:"comments"`
	Hasvisible         bool          `json:"hasvisible"`
	PreviousCursor     int           `json:"previous_cursor"`
	NextCursor         int           `json:"next_cursor"`
	TotalNumber        int           `json:"total_number"`
	SinceID            int           `json:"since_id"`
	MaxID              int           `json:"max_id"`
	LikeCounts         int           `json:"like_counts"`
	TextRaw            string        `json:"text_raw"`
}
